### ISSUE TITLE
Trouble rebuilding .uf2 CircuitPython firmware image

### ISSUE THREAD

**Issue by ajlennon** [Swarm-Technologies/Getting-Started#1]
Hi,

I wanted to build my own CircuitPython firmware image for a couple of reasons

- I like to know I can maintain firmware and change it's components if I want to
- I think a WEBREPL facility would be a huge bonus for me to be able to develop remotely using e.g. Jupyter when the unit can't be wired directly to my development system.

I tried building the 7.0.0.alpha.5 release for installation on the unit. This build ok but

- When I copied it to the USB driver as the instructions seem to say it wasn't installed correctly
- I couldn't get the unit to boot into a boot mode with a boot drive

I'm not sure which is the correct procedure for the existing UF2 firmware image which is 7.0.0.alpha.3 I think

Then I tried building 7.0.0.alpha.3 and this build succesfully but I was again unable to get this into the board via the UF2 bootloader.

My own builds have both UF2 and .bin artifacts so I was able to use esptool.py to write my own builds to the board.

However there is no .bin file in the repo so I couldn't use this method to write the original firmware back.

- it would be useful to have the bin file available for esptool.py recover where necessary

In the end I followed the instructions here https://learn.adafruit.com/adafruit-metro-esp32-s2/install-uf2-bootloader

This allowed me to blow a basic bootloader in with esptool.py then boot in "bootloader mode" and write the original UF2 alpha.3 image by copying it to the drive. So that got me back to where I started

The problem with both my own alpha.3 and alpha.5 images is that they don't drive the OLED display correctly. It is corrupted I will see if I can find an image.

So in recap

- it would help to have the original .bin image in the repo too or a process to extract it from the uf2
- there's some kind of issue building our own copies of the firmware.

**Comment by whilb** [comment]
Hi @ajlennon,

Going forward, CircuitPython binaries for the FeatherS2 will be bundled with each [release](https://github.com/Swarm-Technologies/Getting-Started/releases/tag/FeatherS2-v1.2).
